language: c

os:
  - linux
  - osx

osx_image:
  - xcode9.2

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install -y valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgirnd; fi

script: travis_wait 60 make test
